// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzavAj9G4i-dJ1KU0y6nG38vlND_XR0aA',
    appId: '1:36286418571:web:15593276a89aca3c7bce8e',
    messagingSenderId: '36286418571',
    projectId: 'spm-app-e91be',
    authDomain: 'spm-app-e91be.firebaseapp.com',
    storageBucket: 'spm-app-e91be.appspot.com',
    measurementId: 'G-D0QRQJC506',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8o_2E2GJaoc0uShoyiJpwWGmdY_ZT0RQ',
    appId: '1:36286418571:android:885e7ed4f4cf9e687bce8e',
    messagingSenderId: '36286418571',
    projectId: 'spm-app-e91be',
    storageBucket: 'spm-app-e91be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDweqVswLuJiaCNV5tGKAAvkhYUIVWQslQ',
    appId: '1:36286418571:ios:bd20c69fc0bb38307bce8e',
    messagingSenderId: '36286418571',
    projectId: 'spm-app-e91be',
    storageBucket: 'spm-app-e91be.appspot.com',
    iosBundleId: 'com.example.spmProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDweqVswLuJiaCNV5tGKAAvkhYUIVWQslQ',
    appId: '1:36286418571:ios:bd20c69fc0bb38307bce8e',
    messagingSenderId: '36286418571',
    projectId: 'spm-app-e91be',
    storageBucket: 'spm-app-e91be.appspot.com',
    iosBundleId: 'com.example.spmProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzavAj9G4i-dJ1KU0y6nG38vlND_XR0aA',
    appId: '1:36286418571:web:14ef46f06d2713527bce8e',
    messagingSenderId: '36286418571',
    projectId: 'spm-app-e91be',
    authDomain: 'spm-app-e91be.firebaseapp.com',
    storageBucket: 'spm-app-e91be.appspot.com',
    measurementId: 'G-T757WRF8XT',
  );
}
